spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/job-offers
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

joboffers:
  offer:
    scheduler:
      delayTime: "* * */3 * * *"
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057
          connectTimeout: 5000
          readTimeout: 5000

scheduling:
  enabled: true