joboffers:
  offer:
    cron: "* * */3 * * *"

#spring:
#  data:
#    mongodb:
#      uri: mongodb://admin:admin@localhost:27017/job-offers
#
#joboffers:
#  offer:
#    http:
#      client:
#        config:
#          uri: localhost
#
#          port: 123123